
stages:
  - format
  - docker_build
  - build
  - test
  - release
  - publish

include:
  - gitlab/common.yml
  - gitlab/android.yml
  - gitlab/ios.yml
  - gitlab/python.yml
  - gitlab/docker.yml

## disables MR-triggered pipelines and allows only branch-triggered pipelines
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always



test_format:
  extends: .debian-image
  stage: format
  needs: []
  script:
    - ./tools/format.sh && git diff --exit-code



build_gcc_bullseye:
  extends: .debian-image
  stage: build
  needs: [ test_format ]
  script:
    - ./tools/build.sh --gcc --buildtype release --no-deps-rebuild --external-deps-dir /prebuild/gcc --parallel 16


build_clang_bullseye:
  extends: .debian-image
  stage: build
  needs: [ test_format ]
  script:
    - ./tools/build.sh --clang --buildtype release --no-deps-rebuild --external-deps-dir /prebuild/clang --parallel 16 --enable-tests
  artifacts:
    expire_in: 2 hrs
    paths:
      - build-clang/tests
      - build-clang/CTestTestfile.cmake

test_clang_bullseye:
  extends: .debian-image
  stage: test
  needs: [build_clang_bullseye]
  script:
    - cd build-clang
    - ctest



test_rust:
  extends: .debian-image
  needs: []
  stage: test
  variables:
    OPENSSL_DIR: "/prebuild/clang/openssl/build/"
    WALLY_DIR: "/prebuild/clang/libwally-core/build/lib"
    RUSTFLAGS: "-C instrument-coverage"
    RUST_BACKTRACE: "1"
    LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"
  script:
    - cargo nextest run --profile ci --manifest-path subprojects/gdk_rust/Cargo.toml
    - grcov --binary-path subprojects/gdk_rust/target/debug/ -t cobertura --branch --ignore-not-existing --ignore "*cargo*" -o coverage.xml -p `pwd` subprojects/gdk_rust
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 5 days
    paths:
      - subprojects/gdk_rust/target/nextest/ci/junit.xml
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: subprojects/gdk_rust/target/nextest/ci/junit.xml
  allow_failure: true

rust_audit:
  extends: .debian-image
  needs: []
  stage: test
  allow_failure: true
  script:
    - cd subprojects/gdk_rust/
    - cargo audit -D warnings --ignore RUSTSEC-2021-0127



build_clang_fedora:
  extends: .fedora-image
  stage: build
  needs: [ test_format ]
  script:
    - source /root/.cargo/env
    - ./tools/build.sh --clang --buildtype release --no-deps-rebuild --external-deps-dir /prebuild/clang --parallel 16

build_gcc_ubuntu20.04:
  extends: .ubuntu-image
  stage: build
  needs: [ test_format ]
  script:
    - ./tools/build.sh --gcc --buildtype release --no-deps-rebuild --external-deps-dir /prebuild/gcc --parallel 16



build_mingw64_windows:
  extends: .debian-image
  stage: build
  needs: [ test_format ]
  variables:
    INSTALL_PATH: "install-gdk"
  script:
    - ./tools/build.sh --mingw-w64 --buildtype release --no-deps-rebuild --external-deps-dir /prebuild/mingw-w64 --parallel 16



build_clang_osx:
  extends:
    - .osx_env
    - .py_release
  parallel:
    matrix:
      - RUNNER: [ia, m1]
  tags:
    - osx-$RUNNER
  stage: build
  needs: [ test_format ]
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r ./tools/requirements.txt
    - PREBUILT_DIR="$CI_BUILDS_DIR/$PREBUILT_SUBDIR/clang-osx"
    - if [[ ! -d "$PREBUILT_DIR" ]]; then ./tools/builddeps.sh --parallel 16 --clang --prefix $PREBUILT_DIR; fi
    - touch $PREBUILT_DIR/last_use # marking last use to help out during sweeping operations
    - ./tools/build.sh --clang --buildtype release --install $INSTALL_PATH --no-deps-rebuild --python-version venv --external-deps-dir $PREBUILT_DIR --parallel 16
    - mkdir -p wheelhouse
    - cp $INSTALL_PATH/share/python/* wheelhouse



apidocs:
  extends: .debian-image
  stage: build
  needs: [ test_format ]
  artifacts:
    expire_in: 14 days
    when: on_success
    paths:
    - apidocs.tar.gz
  script:
    - virtualenv -p python3 .venv
    - source .venv/bin/activate
    - pip3 install -r docs/requirements.txt
    - sphinx-build -b html -a -c docs/source docs/source docs/build/html
    - cd docs/build && tar czf ../../apidocs.tar.gz html/ && cd ../..
    - deactivate




