[package]
name = "gdk-common"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>", "William Casarin <jb55@jb55.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.11.1"
libc = "0.2"
hex = "0.4.0"
rand = "0.6.5"
bitcoin = { version = "0.27", features = ["use-serde"] }
#elements = { version = "0.18", features = ["serde-feature"] }
elements = { git = "https://github.com/ElementsProject/rust-elements", rev = "53d5729f8cdc3623f9f110edba86aeaa9059af5b", features = ["serde-feature"] }
# We need to pin half (transitive dep from serde_cbor) to stay compatible with Rust 1.49.0
half = "~1.7"

