[package]
name = "gdk-rust"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>", "Nadav Ivgi <nadav@shesek.info>"]
license = "(MIT)"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[features]
android_log = ["android_logger"]

[dependencies]
rand = "0.7.3"
gdk-electrum = { path = "gdk_electrum", features = ["android_log"] }
gdk-common = { path = "gdk_common" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
hex = "0.4.0"
log = "0.4.8"
android_logger = { version = "0.8.6", optional = true }
url = "1.7.2"
ureq = { version = "1.5.5", features = ["json", "socks-proxy"] }
# We need to pin half (transitive dep from serde_cbor) to stay compatible with Rust 1.49.0
half = "~1.7"


[dev-dependencies]
tempdir = "0.3.7"
electrum-client = { version = "0.8.0", default-features = false, features = [ "proxy", "use-openssl" ] }
bitcoin = { version = "0.27.0", features = [ "use-serde" ] }
#elements = { version = "0.18", features = ["serde-feature"] }
elements = { git = "https://github.com/ElementsProject/rust-elements", rev = "53d5729f8cdc3623f9f110edba86aeaa9059af5b", features = ["serde-feature"] }
# TODO: remove "legacy" feature when upgrading electrs binaries
electrsd = { version = "0.10.0", features = [ "legacy", "trigger" ] }
# We need to pin ureq (transitive dep from electrsd) to stay compatible with Rust 1.49.0
ureq = "~2.2"

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
codegen-units = 1
incremental = false

# FIXME: LTO is required to fix building on iphone
[profile.dev]
lto = true
debug = true
debug-assertions = true
panic = 'abort'
